CREATE TABLE category
(
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(30) NOT NULL
);

CREATE TABLE menu_item
(
    dish_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dish_name VARCHAR(255) NOT NULL,
    dish_image BLOB,
    category INT,
    price FLOAT NOT NULL,
    available BOOLEAN NOT NULL,
    FOREIGN KEY (category) REFERENCES category (category_id)
);