CREATE TABLE menu_item
(
    dish_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dish_name VARCHAR(255) NOT NULL,
    dish_image BLOB,
    category VARCHAR(255) NOT NULL,
    price FLOAT NOT NULL,
    available BOOLEAN NOT NULL
);