INSERT INTO CATEGORY(CATEGORY_NAME) VALUES('Antipasti');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES('Primi piatti');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES('Secondi di carne');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES('Secondi di pesce');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES('Contorni');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES('Dessert');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES('Bevande');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES('Caffè e amari');

INSERT INTO MENU_ITEM(DISH_NAME, DISH_IMAGE, CATEGORY, PRICE, AVAILABLE) VALUES('Antipasto di terra', FILE_READ('classpath:images/antipasto-di-terra.png'), 1, 18.80, TRUE);
INSERT INTO MENU_ITEM(DISH_NAME, DISH_IMAGE, CATEGORY, PRICE, AVAILABLE) VALUES('Cozze alla marinara', FILE_READ('classpath:images/cozze-alla-marinara.png'), 1, 15.00, TRUE);
INSERT INTO MENU_ITEM(DISH_NAME, DISH_IMAGE, CATEGORY, PRICE, AVAILABLE) VALUES('Crudo e bufala', FILE_READ('classpath:images/crudo-e-bufala.png'), 1, 16.79, FALSE);
INSERT INTO MENU_ITEM(DISH_NAME, CATEGORY, PRICE, AVAILABLE) VALUES('Carbonara', 2, 16.8, TRUE);
INSERT INTO MENU_ITEM(DISH_NAME, CATEGORY, PRICE, AVAILABLE) VALUES('Noci, gorgonzola e radicchio', 2, 17.8, TRUE);
INSERT INTO MENU_ITEM(DISH_NAME, CATEGORY, PRICE, AVAILABLE) VALUES('Pescatora', 2, 19.8, TRUE);