INSERT INTO MENU_ITEM(DISH_NAME, CATEGORY, PRICE, AVAILABLE) VALUES('Antipasto di terra', 'starter', 18.79, TRUE);
INSERT INTO MENU_ITEM(DISH_NAME, CATEGORY, PRICE, AVAILABLE) VALUES('Cozze alla marinara', 'starter', 15.79, TRUE);
INSERT INTO MENU_ITEM(DISH_NAME, CATEGORY, PRICE, AVAILABLE) VALUES('Crudo e bufala', 'starter', 16.79, TRUE);