INSERT INTO menu (dish_name,category,available)
    VALUES
    ("Antipasto di terra","starter",TRUE),
    ("Misto di fritti","starter",TRUE),
    ("Cozze alla marinara","starter",TRUE),
    ("Amatriciana","first course",TRUE),
    ("Pasta noci, gorgonzola e radicchio","first course",TRUE),
    ("Spaghetti allo scoglio","first course",TRUE),
    ("Carbonara","first course",TRUE),
    ("Trancio di salmone in agrodolce","fish",TRUE),
    ("Pesce spada alla siciliana","fish",TRUE),
    ("Grigliata mista","fish",TRUE),
    ("Frittura di pesce","fish",TRUE),
    ("Filetto di maiale in salsa","meat",TRUE),
    ("Cotoletta di pollo","meat",TRUE),
    ("Tagliata di picanha","meat",TRUE),
    ("Patatine fritte","side",TRUE),
    ("Patate al forno","side",TRUE),
    ("Verdure grigliate","side",TRUE),
    ("Insalata mista","side",TRUE),
    ("Panna cotta","dessert",TRUE),
    ("Tiramisù","dessert",TRUE),
    ("Cheescake frutti di bosco","dessert",TRUE),
    ("Acqua naturale","drinks",TRUE),
    ("Acqua frizzante","drinks",TRUE),
    ("Coca-Cola","drinks",TRUE),
    ("Aranciata","drinks",TRUE),
    ("Caffè","drinks",TRUE),
    ("Vino rosso della casa","alcohol",TRUE),
    ("Vino bianco della casa","alcohol",TRUE),
    ("Birra Ichnusa","alcohol",TRUE),
    ("Birra Ichnusa non filtrata","alcohol",TRUE);